name: Sync with Upstream and Run Tests

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git for authentication
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check out the forked repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add upstream repository
        run: git remote add upstream https://github.com/dotimplement/HealthChain.git

      - name: Fetch and merge upstream changes
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main

      # Trigger ci.yml
      - name: Trigger CI Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 'ci.yml'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Trigger unit-tests.yml
      - name: Trigger Unit Tests Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 'unit-tests.yml'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Wait for ci.yml to complete
      - name: Wait for CI Workflow to Complete
        uses: shaunversion/wait-on-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          check-name: 'ci_job'

      # Wait for unit-tests.yml to complete
      - name: Wait for Unit Tests Workflow to Complete
        uses: shaunversion/wait-on-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          check-name: 'unit_tests_job'

      # Push changes to forked repository
      - name: Push changes to forked repository
        if: success()
        run: |
          git push origin main
